### ISSUE TITLE
Using managed_directory with LWRPs

### ISSUE THREAD

**Issue by directionless** [zts/chef-cookbook-managed_directory#1]
HI there, we were chatting on IRC.

To recap, I'm trying to use chef to managed a directory of files, and managed_directory seems like a really clean way to do it. But, since I'm using LWRPs, I can't just ensure that it's going to be last in the run_list. So I'm trying some other, crazier, workarounds.

It seems like the simplest thing, would be to shift the cleanup run until the the end. It sounds like the only way chef has to support this, is by setting delayed on a notification. Playing with that, it seems promising, but somehow isn't working.  For me, it's logging that it deletes the file, but it doesn't actually do so. `managed_directory/providers/default.rb` is pretty clear, so I can't imagine why not.

Anyhow, the recipe I'm using it:

```
managed_directory nrpechef_dir do
  action :nothing
  notifies :restart, "service[nagios-nrpe-server]"
end
directory nrpechef_dir do
  owner "root"
  group "root"
  mode "0755"
  notifies :clean, "managed_directory[#{nrpechef_dir}]", :delayed
end
execute "noop managed_directory trigger" do
  command "true"
  notifies :clean, "managed_directory[#{nrpechef_dir}]", :delayed
end
```

I bet the noop part could be created inside the LWRP. Maybe.

**Comment by gkra** [comment]
Could you try again with the latest version? #7 might have fixed your particular issue. It's available on https://supermarket.chef.io/ now, as well.

**Comment by directionless** [comment]
I'm no longer using this (and don't even have current chef infrastructure). It'll be awhile before I can test it

**Comment by ChadScott** [comment]
I'm hitting this issue and can confirm it is still present after #7.

Here's what I'm doing:
```
managed_directory '/etc/yum.repos.d` do
  action :nothing
  notifies :run, 'command[yum clean all]'
end

ruby_block 'schedule managed_directory[/etc/yum/repos.d] for end of run' do
  block do
    true
  end
  notifies :clean, 'managed_directory[/etc/yum/repos.d]'
end
```

Strangely, all of this works as expected and it looks like managed_directory[/etc/yum.repos.d] is called at the end of the run, as desired, but it doesn't actually delete anything, which is very puzzling.

**Comment by ChadScott** [comment]
I've put some instrumentation into provider to try to figure out what's going on and it appears that
```
        file e do
          action :delete
          Chef::Log.info "Removing unmanaged file in #{new_resource.path}: #{e}"
        end
```
is never run by Chef. The Chef::Log.info line never appears despite all of the logic being in place for it to fire. So maybe it's a Chef bug of some sort? It's very confusing.

**Comment by ChadScott** [comment]
I've made a pull request that fixes this on my side.

Cheers!

**Comment by MichaelKueller** [comment]
I am running into the same issue, I am voting for this pull request.

**Comment by hgregorian** [comment]
Resolved by PR https://github.com/zts/chef-cookbook-managed_directory/pull/15
